sudo: required
dist: focal
language: cpp

os:
  - linux

addons:
  apt:
    packages:
      - libsnappy-dev
      - libgoogle-glog-dev
      - libprotobuf-dev
      - protobuf-compiler

compiler:
  - gcc

language: cpp

script: make
