sudo: required
dist: focal
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['libsnappy-dev', 'libprotobuf-dev', 'protobuf-compiler', 'libgoogle-glog-dev']

compiler:
  - gcc

language: cpp

script: make
