sudo: required
dist: focal
language: cpp

os:
  - linux

env:
  global:
    - PROTOBUF_VERSION=3.20.3

install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-cpp-${PROTOBUF_VERSION}.tar.gz
  - tar xvf protobuf-cpp-$PROTOBUF_VERSION.tar.gz
  - (cd protobuf-$PROTOBUF_VERSION && ./configure --prefix=/usr && make && sudo make install )

addons:
  apt:
    packages: ['libsnappy-dev', 'libprotobuf-dev', 'libgoogle-glog-dev']

compiler:
  - gcc

language: cpp

script: make
